### ISSUE TITLE
Post code for best models

### ISSUE THREAD

**Issue by JohnM-TX** [JohnM-TX/ToxicWords#4]

**Comment by JasonEricZhan** [comment]
update my CV version, also produce the 10 out of fold

**Comment by JasonEricZhan** [comment]
Also add the word-net preprocessing, if anyone want to use it, put it at the segment when you done the all preprocessing, including correct the spelling change the punctuation.  Notice that I assume the machine has 4 cpu to run, so if run in your machine you can change it by your self.

**Comment by JasonEricZhan** [comment]
But this kind of word-net preprocessing I might use only in one of my model for diversity.
