### ISSUE TITLE
Scan other teams' code for useful ideas

### ISSUE THREAD

**Issue by JohnM-TX** [JohnM-TX/ToxicWords#5]

**Comment by JohnM-TX** [comment]
Add capsule net
https://www.kaggle.com/chongjiujjin/capsule-net-with-gru?scriptVersionId=2824792/notebook

**Comment by JasonEricZhan** [comment]
Alternative way to stacking, if stacking is not work, or maybe this can do at third layer, stack at second
https://www.kaggle.com/reppic/lazy-ensembling-algorithm
